cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>', views.cart_add, name='cart_add'),
    path('remove/<product_id>', views.cart_remove, name='cart_remove'),
]

dip/urls.py
"""
dip URL Configuration

"""
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from dip import settings
from dshop.views import IndexView, ArticleView, ArticleDetail

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dshop/', include('dshop.urls', namespace='dshop')),
    path('payment/', include('robokassa.urls', namespace='robokassa')),
    path('articles/', ArticleView.as_view(), name='articles_list'),
    path('articles/<slug>/', ArticleDetail.as_view(), name='articles_detail_url'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dshop/urls.py
from django.urls import path
from dshop import views
from dshop.views import ProductDetail, ProductListView

app_name = 'dshop'

urlpatterns = [
    # path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_list/', views.product_list, name='product_list'),
    path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('<slug>/', views.product_list, name='product_list_by_category'),
    # path('<slug>/', ProductListCategoryView.as_view(), name='product_list_by_category'),

]

orders/urls.py
from django.urls import path
from .views import OrderCreate, OrderCreated

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreate.as_view(), name='order_create'),
    path('created/', OrderCreated.as_view(), name='created'),

]

cart/forms.py
from django import forms
from crispy_forms.helper import FormHelper

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

    class Meta:
        verbose_name = 'Количество'

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from dshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends "dshop/base_dshop.html" %}
{% load static %}
{% block title %}
    Ваша корзина:
{% endblock %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h4 class="display-4">Корзина покупок:</h4>
        </div>
    </div>
    <div class="container mt-3">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Изображение</th>
                <th scope="col">Товар</th>
                <th scope="col">Количество</th>
                <th scope="col">Удалить</th>
                <th scope="col">Цена</th>
                <th scope="col">Стоимость</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{{ product.image.url }}" height="100">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td><a href="{% url "cart:cart_remove" product.id %}">Удалить из корзины</a></td>
                        <td class="num">{{ item.price }} руб.</td>
                        <td class="num">{{ item.total_price }} руб.</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td><h6></h6></td>
                <td colspan="4"><h6>Стоимость заказа</h6></td>
                <td class="num"><h6>{{ cart.get_total_price }} руб.</h6></td>
            </tr>
            </tbody>
        </table>
        <p class="text-center" >
            <a href="{% url "dshop:product_list" %}"
            <button type="button" class="btn btn-secondary btn-lg">Продолжить покупки</button>
            </a>
            {% if cart.get_total_price != 0 %}
                <a href="{% url "orders:order_create" %}"
                <button type="button" class="btn btn-primary btn-lg">Перейти к оформлению</button>
                </a>
            {% endif %}
        </p>
    </div> <!-- /container -->
{% endblock %}