accounts/urls.py
from django.contrib.auth import views
from django.contrib.auth.views import LoginView
from django.urls import path
# from accounts import views

from django.urls import path

from accounts.views import EmailRegisterFormView

app_name = 'accounts'


urlpatterns = [
    path('register/', EmailRegisterFormView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

]

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>', views.cart_add, name='cart_add'),
    path('remove/<product_id>', views.cart_remove, name='cart_remove'),
]

dip/urls.py
"""
dip URL Configuration

"""
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from dip import settings
from dshop.views import IndexView, ArticleView, ArticleDetail

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dshop/', include('dshop.urls', namespace='dshop')),
    path('payment/', include('robokassa.urls', namespace='robokassa')),
    path('articles/', ArticleView.as_view(), name='articles_list'),
    path('articles/<slug>/', ArticleDetail.as_view(), name='articles_detail_url'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dshop/urls.py
from django.urls import path
from dshop import views
from dshop.views import ProductDetail, ProductListView

app_name = 'dshop'

urlpatterns = [
    # path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_list/', views.product_list, name='product_list'),
    path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('<slug>/', views.product_list, name='product_list_by_category'),
    # path('<slug>/', ProductListCategoryView.as_view(), name='product_list_by_category'),

]

templates/base.html
{% load static %}
{% load mptt_tags %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Dshop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body class="" data-gr-c-s-loaded="true">
<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url "index" %}">Магазин Dshop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url "articles_list" %}">Статьи и обзоры <span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url "dshop:product_list" %}" id="navbarDropdown"
                   role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Каталог товаров
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <ul>
                        {% recursetree categories %}
                            <li>
                                <a class="dropdown-item" href="{{ node.get_absolute_url }}">{{ node.name }}</a>
                                <ul>
                                    {{ children }}
                                </ul>
                            </li>
                        {% endrecursetree %}
                    </ul>
                </div>
            </li>
        </ul>

        {% if user.is_authenticated %}
            <nav class="navbar navbar-dark bg-dark">
              <span class="navbar-text">
                Привет, {{ user.username }}!
              </span>
            </nav>

            <a class="btn btn-sm align-middle btn-outline-secondary" role="button"
               href="{% url "accounts:logout" %}">
                Выйти</a>

        {% else %}
            <a class="btn btn-sm align-middle btn-outline-secondary" role="button"
               href="{% url "accounts:login" %}">
                Войти</a>
            <a class="btn btn-sm align-middle btn-outline-secondary" role="button"
               href="{% url "accounts:register" %}">
                Регистрация</a>

        {% endif %}

        <a class="btn btn-sm align-middle btn-outline-secondary" role="button"
           href="{% url "cart:cart_detail" %}">
            Корзина</a>

    </div>
</nav>

{% block content %}

{% endblock %}

<hr>
<footer class="container">
    <p>© Магазин Dshop 2020</p>
</footer>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>