dip/urls.py
"""
dip URL Configuration

"""
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from dip import settings
from dshop.views import IndexView, ArticleView, ArticleDetail

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dshop/', include('dshop.urls', namespace='dshop')),
    path('payment/', include('robokassa.urls', namespace='robokassa')),
    path('articles/', ArticleView.as_view(), name='articles_list'),
    path('articles/<slug>/', ArticleDetail.as_view(), name='articles_detail_url'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dshop/urls.py
from django.urls import path
from dshop import views
from dshop.views import ProductDetail, ProductListView

app_name = 'dshop'

urlpatterns = [
    # path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_list/', views.product_list, name='product_list'),
    path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('<slug>/', views.product_list, name='product_list_by_category'),
    # path('<slug>/', ProductListCategoryView.as_view(), name='product_list_by_category'),

]

orders/urls.py
from django.urls import path
from .views import OrderCreate, OrderCreated

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreate.as_view(), name='order_create'),
    path('created/', OrderCreated.as_view(), name='created'),

]

robokassa/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from robokassa.views import PaymentProcessView, SuccessResultView, FailResultView

app_name = 'robokassa'

urlpatterns = [
    path('robokassa/', PaymentProcessView.as_view(), name='payment_url'),
    path('success/', csrf_exempt(SuccessResultView.as_view()), name='success'),
    path('fail/', csrf_exempt(FailResultView.as_view()), name='fail'),

]

orders/models.py
from django.conf import settings
from django.db import models
from dshop.models import Product


class Order(models.Model):
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True,
                                 verbose_name='Зарегистрированный пользователь')
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    email = models.EmailField()
    address = models.CharField(max_length=250, verbose_name='Адрес')
    phone = models.CharField(max_length=25, verbose_name='Телефон')
    city = models.CharField(max_length=100, verbose_name='Город')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Изменен')
    paid = models.BooleanField(default=False, verbose_name='Оплачено?')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы(ов)'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items', verbose_name='Заказ')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items', verbose_name='Детали '
                                                                                                            'заказа')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    class Meta:
        verbose_name = 'Заказанный товар'
        verbose_name_plural = 'Заказанные товары'

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'phone', 'city']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))

orders/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import FormView, CreateView, TemplateView
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart


class OrderCreate(FormView, CreateView):
    form_class = OrderCreateForm
    model = Order
    template_name = 'orders/create.html'
    success_url = reverse_lazy('orders:created')

    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        form = self.form_class(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if request.user.is_authenticated:
                order.username = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
        return HttpResponseRedirect(self.success_url)

    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        user = request.user
        data = {}
        if user.is_authenticated:
            data["last_name"] = user.last_name
            data["first_name"] = user.first_name
            data["email"] = user.email
        form = self.form_class(initial=data)
        return render(request, 'orders/create.html',
                      {'cart': cart,
                       'form': form})


class OrderCreated(TemplateView):
    template_name = 'orders/created.html'
    model = Order
    extra_context = {'order': Order.objects.first().id}

templates/orders/create.html
{% extends "dshop/base_dshop.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Оформление заказа
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h4 class="display-4">Оформление заказа:</h4>
        </div>
    </div>
    <div class="container mt-3">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Количество</th>
                <th scope="col">Товар</th>
                <th scope="col">Цена</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                <tr>
                    <td>{{ item.quantity }} шт.</td>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.total_price }} руб.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <h6> Итого: {{ cart.get_total_price }} руб.</h6>

        <div class="alert alert-dark" role="alert">
            Ваши контактые данные:
        </div>

        <form action="." method="post" class="order-form">
            <div class="row">
                <div class="col-6">
                    {{ form.first_name|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.last_name|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.address|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.phone|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.city|as_crispy_field }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary btn-lg">Подтвердить заказ</button>
            {% csrf_token %}
        </form>
    </div> <!-- /container -->
{% endblock %}

templates/orders/created.html
{% extends "dshop/base_dshop.html" %}

{% block title %}Спасибо, заказ оформлен!{% endblock %}

{% block content %}
    <div class="container mt-3">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-12">
                <div class="card text-center">
                    <div class="card-header">
                        Завершение обработки заказа.
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Ваш заказ успешно оформлен!</h5>
                        <p class="card-text">Номер Вашего заказа <strong>{{ order }}</strong>.</p>
                        <a href="{% url "dshop:product_list" %}" class="btn btn-primary">Смотреть еще товары</a>
                        <p class="card-title">Или оплатить онлайн!</p>
                        <form name="form" method="POST" action="{% url 'robokassa:payment_url' %}">
                            {% csrf_token %}
                            <input class="btn btn-primary" type="submit" name="submit"
                                   value="Оплатить онлайн РОБОКАССА"/>
                        </form>
                        <p class="card-text"><strong>(Имитация платежа)</strong></p>
                    </div>
                    <div class="card-footer text-muted">
                    </div>
                </div>
            </div>

        </div>
    </div>

    </div> <!-- /container -->
{% endblock %}