cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>', views.cart_add, name='cart_add'),
    path('remove/<product_id>', views.cart_remove, name='cart_remove'),
]

dip/urls.py
"""
dip URL Configuration

"""
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from dip import settings
from dshop.views import IndexView, ArticleView, ArticleDetail

urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dshop/', include('dshop.urls', namespace='dshop')),
    path('payment/', include('robokassa.urls', namespace='robokassa')),
    path('articles/', ArticleView.as_view(), name='articles_list'),
    path('articles/<slug>/', ArticleDetail.as_view(), name='articles_detail_url'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dshop/urls.py
from django.urls import path
from dshop import views
from dshop.views import ProductDetail, ProductListView

app_name = 'dshop'

urlpatterns = [
    # path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_list/', views.product_list, name='product_list'),
    path('product/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('<slug>/', views.product_list, name='product_list_by_category'),
    # path('<slug>/', ProductListCategoryView.as_view(), name='product_list_by_category'),

]

dshop/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    name = models.CharField(max_length=200, db_index=True, unique=True, verbose_name='Название категории')
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True,
                            blank=True, related_name='children', verbose_name='Родитель')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('dshop:product_list_by_category',
                       args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Категория')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='Индекс')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Изображение')
    description = RichTextUploadingField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    stock = models.PositiveIntegerField(verbose_name='Наличие')
    available = models.BooleanField(default=True, verbose_name='Товар включен')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def get_absolute_url(self):
        return reverse('dshop:product_detail',
                       args=[self.slug])

    def __str__(self):
        return self.name


class Article(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='articles', verbose_name='Товар')
    title = models.CharField(max_length=256, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=256, db_index=True)
    text = RichTextUploadingField(db_index=True, verbose_name='Текст')
    published_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    image = models.ImageField(null=True, blank=True, verbose_name='Изображение', )

    class Meta:
        verbose_name = 'Обзор'
        verbose_name_plural = 'Обзоры'

    def get_absolute_url(self):
        return reverse('articles_detail_url',
                       args=[self.slug])

    def __str__(self):
        return self.title

dshop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category, Article
from cart.forms import CartAddProductForm
from django.views.generic import ListView, DetailView, FormView


class IndexView(ListView):
    template_name = 'dshop/index.html'
    queryset = Article.objects.all().order_by('published_at')
    context_object_name = 'articles'


class ProductListView(ListView):
    model = Category
    template_name = 'dshop/product/list.html'
    slug_field = 'root'
    products = Product.objects.filter(available=True)
    category = get_object_or_404(Category, slug=slug_field)
    products = products.filter(category__in=category.get_descendants(include_self=True))
    context_object_name = products


def product_list(request, slug='root'):
    template = 'dshop/product/list.html'
    products = Product.objects.filter(available=True)
    category = get_object_or_404(Category, slug=slug)
    products = products.filter(category__in=category.get_descendants(include_self=True))
    return render(request, template,
                  {'category': category,
                   'products': products})


class ProductDetail(FormView, DetailView):
    model = Product
    template_name = 'dshop/product/detail.html'
    form_class = CartAddProductForm
    queryset = Product.objects.filter(available=True)
    context_object_name = 'product'


class ArticleView(ListView):
    template_name = 'dshop/articles_list.html'
    queryset = Article.objects.all().order_by('published_at')
    context_object_name = 'articles'


class ArticleDetail(DetailView):
    model = Article
    template_name = 'dshop/article_detail.html'
    context_object_name = 'article'

templates/dshop/product/detail.html
{% extends "dshop/base_dshop.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-12">
                <h1>{{ product.name }}</h1>
                <img src="{{ product.image.url }}" width="300">
                <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
                <p> Цена: {{ product.price }} руб.</p>
                {% autoescape off %}{{ product.description|linebreaks }}{% endautoescape %}
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                    <div class="col-1">
                        {{ form.quantity|as_crispy_field}}
                        <input type="submit" class="btn btn-primary" value="Добавить в корзину">
                        {% csrf_token %}
                    </div>
                </form>
            </div>
        </div>

    </div> <!-- /container -->

{% endblock content %}

templates/dshop/product/list.html
{% extends "dshop/base_dshop.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}

    <div class="container">
        <!-- Example row of columns -->
        <div class="jumbotron">
            <div class="container">
                <h4 class="display-4">{% if category %}{{ category.name }}{% else %}Products{% endif %}</h4>
            </div>
        </div>
        <div class="container mb-5">
            <div class="row">
                {% for product in products %}
                    <div class="col-md-4">
                        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{ product.image.url }}" height="250"></a>
                        <p> Цена: {{ product.price }} руб.</p>
{#                        <form>#}
{#                            <input type="submit" class="btn btn-secondary" value="Подробнее">#}
{##}
{#                        </form>#}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="alert alert-dark" role="alert">
            Выбираейте с удовольствием!
        </div>
    </div> <!-- /container -->

{% endblock content %}